name: 'setup-terraform tests'

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  terraform-run-local-failure:
    name: 'Terraform Run Local Failures'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
        working-directory: ./.github/workflows/data/failure
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup Terraform
      uses: ./

    # coerce initial command exit code into:
    # 0 -> 5
    # anything else -> 10
    - name: Terraform Init
      run: $(echo hello) || $(exit 10) && $(exit 5) || [ $? -eq 5 ]

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      id: plan
      run: $(terraform plan --detailed-exitcode) || $(exit 10) && $(exit 5) || [ $? -eq 10 ]

    - name: Terraform Plan2
      id: plan2
      run: $(terraform plan -no-color -detailed-exitcode) || $(exit 10) && $(exit 5) || [ $? -eq 10 ]

    - name: Print Terraform Plan
      run: echo "${{ steps.plan.outputs.stdout }}"
